apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - contianerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: mginx-service
  spec: 
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080